# lightning.pytorch==2.4.0
seed_everything: 42
trainer:
  logger:
    class_path: TensorBoardLogger
    init_args:
      save_dir: "./results/restormer"
  num_nodes: 1
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: "psnr"
        save_weights_only: true
        filename: "{epoch}-{psnr:.2f}"
        save_last: true
        save_top_k: 2
        mode: "max"

    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: "step"

    - class_path: codes.callbacks.ImageSaveCallback
      init_args:
        save_dir: images

  fast_dev_run: false
  max_epochs: 1000
  max_steps: -1
  overfit_batches: 0.0
  val_check_interval: 0.5
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 0
  accumulate_grad_batches: 1
model:
  checkpoints: weights/restormer-sidd-val_avg_psnr=37.92.ckpt
  net:
    class_path: MultiMaskPdDn
    init_args:
      loss_fn:
        class_path: codes.loss.FirstPdMaskLoss
        init_args:
          loss_type: l1
          pd_factor: 5
      pd_train: 5
      pd_val: 2
      dn_net: mmbd
      r3: 0.
      net_param:
        branch_num: 1
        dn_branch: Restormer
        branches_order: [0, 0]
        net_param:
          inp_channels: 3
          out_channels: 3
          dim: 48
          num_blocks: [4, 6, 6, 8]
          num_refinement_blocks: 4
          heads: [1, 2, 4, 8]
          ffn_expansion_factor: 2.66
          bias: False
          LayerNorm_type: "BiasFree"
          dual_pixel_task: False
  optimizer:
    class_path: torch.optim.AdamW
    init_args:
      lr: !!float 1e-4
      betas: [0.9, 0.999]
      weight_decay: 0
  scheduler:
    class_path: torch.optim.lr_scheduler.CosineAnnealingLR
    init_args:
      T_max: 25000
      eta_min: 0
# checkpoint_path: weights/restormer-val_avg_psnr=37.92.ckpt

data:
  batch_size: 2
  train_dataset:
    class_path: codes.data.UnpairDataset
    init_args:
      path: datasets/lmdb/medium_512_512_lmdb
      datatype: lmdb
      max_len: 25000
      crop_size: 160
      augment: True
  val_dataset:
    class_path: codes.data.SIDD_validation
    init_args:
      sidd_val_dir: datasets/SIDD_MAT
      len: 32
  test_dataset:
    class_path: codes.data.SIDD_validation
    init_args:
      sidd_val_dir: datasets/SIDD_MAT
      len: 1280
  predict_dataset:
    class_path: codes.data.SingleImageOrFloderDataset
    init_args:
      path: ./images/test/test_sample.png
