# lightning.pytorch==2.4.0
seed_everything: 42
trainer:
  num_nodes: 1
  logger:
    class_path: TensorBoardLogger
    init_args:
      save_dir: './results/unet'
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: 'val_avg_psnr'
        save_weights_only: true
        filename: '{epoch:02d}-{val_avg_psnr:.2f}'
        save_last: true
        save_top_k: 2
        mode: 'max'

    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: 'step'

    - class_path: codes.callbacks.ImageSaveCallback
      init_args: 
        save_dir: images
      
  fast_dev_run: false
  max_epochs: 100
  max_steps: -1
  overfit_batches: 0.0
  val_check_interval: 100
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 0
  accumulate_grad_batches: 1
model:
  checkpoints: weights/unet-sidd-val_avg_psnr=36.94.ckpt
  net: 
    class_path: MultiMaskPdDn
    init_args:
      loss_fn:
        class_path: codes.loss.FirstPdMaskLoss
        init_args:
          loss_type: l1
          pd_factor: 5
      pd_train: 5
      pd_val: 2
      dn_net: mmbd
      r3: 0.
      net_param:
        branch_num: 1
        dn_branch: Unet
        branches_order: [ 0,0 ]
        net_param:
          in_nc: 3
          out_nc: 3
          n_feature: 128
          blindspot: False
          zero_last: False
  optimizer:
    class_path: torch.optim.AdamW
    init_args:
      lr: !!float 1e-4
      betas: [0.9, 0.999]
      weight_decay: 0
  scheduler:
    class_path: torch.optim.lr_scheduler.CosineAnnealingLR
    init_args:
      T_max: 100
      eta_min: 0
# checkpoint_path: weights/restormer-val_avg_psnr=37.92.ckpt

data:
  train_dataset:
    class_path: codes.data.UnpairDataset
    init_args:
      path: datasets/lmdb/medium_512_512_lmdb
      datatype: lmdb
      max_len: 10000
      crop_size: 160
      augment: True
  val_dataset:
    class_path: codes.data.SIDD_validation
    init_args:
      sidd_val_dir: datasets/SIDD_MAT
      len: 32
  test_dataset:
    class_path: codes.data.SIDD_validation
    init_args:
      sidd_val_dir: datasets/SIDD_MAT
      len: 1280
  predict_dataset:
    class_path: codes.data.SingleImageOrFloderDataset
    init_args:
      path: ./images/test/test_sample.png
